name: Production pipeline

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      USER: ${{ secrets.PRD_SERVER_USER }}
      HOST: ${{ secrets.PRD_SERVER_HOST }}
      REACT_APP_PAGE_LIMIT: 10
      REACT_APP_API_URL: ${{ secrets.PRD_API_URL }}
      REACT_APP_SQUARE_APP_ID: ${{ secrets.PRD_SQUARE_APP_ID }}
      REACT_APP_SQUARE_LOCATION_ID: ${{ secrets.PRD_SQUARE_LOCATION_ID }}
      REACT_APP_SOCKET_URL: ${{ secrets.PRD_SOCKET_URL }}
      REACT_APP_SOCKET_KEY: ${{ secrets.PRD_SOCKET_KEY }}
      REACT_APP_WORKOUT_LOG_TRAINER_SPECIALTIES: ${{ secrets.PRD_WORKOUT_LOG_TRAINER_SPECIALTIES }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies
        run: npm i
      - name: Generate build
        run: npm run build
      - name: Generate TAR GZ
        run: tar -czvf admin.tar.gz ./build
      - uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: ${{ secrets.PRD_SERVER_HOST }}
      - name: Copy files to server
        run: scp admin.tar.gz $USER@$HOST:/var/www
      - name: Unpackage in server
        run: >
          ssh $USER@$HOST -t "
          cd /var/www/admin.wellness.com;
          rm -rf *;
          mv ../admin.tar.gz ./;
          tar -xzvf admin.tar.gz;
          mv build/* ./;
          rm -rf build admin.tar.gz;"
